#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Filter VOSTOK profiles from PrusaSlicer configuration file.
Removes all profiles that don't contain "VOSTOK" in their name.
"""

import os
import re
import sys

def filter_vostok_profiles():
    filename = "prusaslicer_vostok_config_example.ini"
    
    # Get directory where script is located
    script_dir = os.path.dirname(os.path.abspath(__file__))
    filepath = os.path.join(script_dir, filename)
    
    if not os.path.exists(filepath):
        print(f"Error: File '{filename}' not found in {script_dir}")
        input("Press Enter to exit...")
        sys.exit(1)
    
    print(f"Processing {filename}...")
    
    # New header
    header_lines = [
        "# K3D VOSTOK example configuration",
        "# by Dmitry Sorkin (dbsorkin@gmail.com)",
        "# CC-BY 3.0"
    ]
    
    # Read file
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.read().splitlines()
    
    skip_first = True
    in_section = False
    keep_section = False
    section_buffer = []
    result = []
    first_section = True
    
    for line in lines:
        # Skip first line with generated comment
        if skip_first and re.match(r'^# generated by PrusaSlicer', line):
            skip_first = False
            continue
        skip_first = False
        
        # Check if this is a section header [type:name]
        match = re.match(r'^\[([^:]+):(.+)\]', line)
        if match:
            # Save previous section if we need to keep it
            if in_section and keep_section:
                if not first_section:
                    result.append('')
                first_section = False
                result.extend(section_buffer)
            
            # Start new section
            in_section = True
            section_name = match.group(2)
            section_buffer = [line]
            
            # Check if section name contains VOSTOK (case insensitive)
            keep_section = bool(re.search(r'VOSTOK', section_name, re.IGNORECASE))
        else:
            # Add line to current section buffer
            if in_section:
                section_buffer.append(line)
    
    # Save last section if needed
    if in_section and keep_section:
        if not first_section:
            result.append('')
        result.extend(section_buffer)
    
    # Combine header and content
    all_lines = header_lines + [''] + result
    
    # Write to file
    with open(filepath, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(all_lines))
        f.write('\n')
    
    # Count sections
    section_count = sum(1 for line in result if line.startswith('['))
    print(f"Done! Kept {section_count} VOSTOK profiles.")
    
    return section_count

if __name__ == "__main__":
    try:
        filter_vostok_profiles()
    except Exception as e:
        print(f"Error: {e}")
        input("Press Enter to exit...")
        sys.exit(1)
    
    print()
    print("Processing complete!")
    input("Press Enter to exit...")
